In [129]:
import numpy as np
import pandas as pd

# One dimentional array

In [130]:
one = np.array([1,2,3,4,5,6,7,8,9,10])
print(one)

[ 1  2  3  4  5  6  7  8  9 10]


In [131]:
print(one.ndim)

1


# Two dimentional array

In [132]:
m_2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(m_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [133]:
print(m_2.ndim)

2


# Indicating the number of arrays you want your data to contain

In [134]:
min_4 = np.array([1,2,3,4,5],ndmin=4)
print(min_4)

[[[[1 2 3 4 5]]]]


In [135]:
print(min_4.ndim)

4


# Three dimentional array

In [136]:
m_3 = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(m_3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [137]:
print(m_3.ndim)

3


In [138]:
print([one[4]*one[2], one[4]-one[2]])

[15, 2]


# Displaying some values/items from an array

In [139]:
print(m_2[1,2])

8


# Locating elements in the three dimentional arrays

In [140]:
print(m_3[0,2,1])

12


# Slicing of items in variables

In [141]:
print(one[1:4])

[2 3 4]


In [153]:
print(one[0:7])

[1 2 3 4 5 6 7]


In [159]:
print(m_2[0,1:4])

[2 3 4]


In [162]:
print(m_3[0,1,1:4])

[7 8 9]
