# Importing Numpy and Pasndas Libraries

In [2]:
import numpy as np
import pandas as pd

# 1a. Creating or generating a 2 by 3 Matrix

In [3]:
matrix1=np.array([[1,2,3],[4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


# Multiplying matrix generated(matrix1) by a scaler of 2

In [4]:
print(matrix1*2)

[[ 2  4  6]
 [ 8 10 12]]


# 1b. Creating a 3 by 3 identity matrix

In [5]:
matrix2=np.array([[[1,0,0],[0,1,0],[0,0,1]]])
print(matrix2)

[[[1 0 0]
  [0 1 0]
  [0 0 1]]]


# 1c. Creating a 1-D array

In [6]:
array1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


# Converting 1-D array to a 2-D array

In [7]:
d=np.reshape(array1,(3,9))
print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


# Converting 2-D array to a 3-D array

In [8]:
array2=np.reshape(d,d.shape+(1,))
print(array2)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]]

 [[19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]]]


# 1d. Creating a 2-D array with elements (1-6) and (7-12)

In [9]:
first=np.array([1,2,3,4,5,6])
second=np.array([7,8,9,10,11,12])
print(second)
print(first)

[ 7  8  9 10 11 12]
[1 2 3 4 5 6]


# Stacking the created array horizontally together

In [10]:
hstack = np.hstack((first,second))
print(hstack)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Stacking the created array vertically together

In [11]:
vstack = np.vstack((first,second))
print(vstack)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# 1e. Creating an equally spaced sequence with a gap of 5 ranging from 0 to 100

In [12]:
my_seq=np.arange(0,100,5)
print(my_seq)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


# 2a. Creating a DataFrame Named students

In [13]:
students = ['Stephen','John','Kojo','Emanuel','Felix']

In [14]:
studentsdf = pd.DataFrame(students,columns=['Name of students'])
studentsdf

Name of students
0          Stephen
1             John
2             Kojo
3          Emanuel
4            Felix

# 2b. Creating Teams DataFrame

In [15]:
teams = [['Hearts of Oak',231,65,80],['Asante Kotoko',100,70,60],['Ebusua Dwarfs',190,50,60],['Sekondi Hassacas',97,43,55]]

In [16]:
teamsdf = pd.DataFrame(teams,columns=['team','GF','GA','PTS'],index=[1,2,3,4])
teamsdf

team   GF  GA  PTS
1     Hearts of Oak  231  65   80
2     Asante Kotoko  100  70   60
3     Ebusua Dwarfs  190  50   60
4  Sekondi Hassacas   97  43   55

# 2c. Creating a dictionary of country names, Capital and their population

In [17]:
country_name = ['Ghana','Nigeria','Togo','Ivory Coast','Senegal','Mali','Guinea', 'Guinea Bissau', 'Benin', 'Liberia','Gambia','Cape Verd','Mauretana','Niger','Bukina Faso','seirre Leone']
capital = ['Accra','Legos','Lome','Yamoussoukro','Dakar','Bamako','Conakry','Bissau','Porto-novo','Monrovia','ouagadougou','Praia','Banjul','Nouakchott','Niamey','Freetown']
population = [23454,45345,78656,78987,90987,45453,123421,87960,4536547,234352,567654,897878,2323218,88890765,4565437,211100098]

# Storing the list within the dictionary

In [18]:
dict_countries = {'country name':country_name,'capital':capital,'population':population}

# Creating the DataFrame from the Dictionary and showing it

In [19]:
countries_df = pd.DataFrame(dict_countries)
countries_df

country name       capital  population
0           Ghana         Accra       23454
1         Nigeria         Legos       45345
2            Togo          Lome       78656
3     Ivory Coast  Yamoussoukro       78987
4         Senegal         Dakar       90987
5            Mali        Bamako       45453
6          Guinea       Conakry      123421
7   Guinea Bissau        Bissau       87960
8           Benin    Porto-novo     4536547
9         Liberia      Monrovia      234352
10         Gambia   ouagadougou      567654
11      Cape Verd         Praia      897878
12      Mauretana        Banjul     2323218
13          Niger    Nouakchott    88890765
14    Bukina Faso        Niamey     4565437
15   seirre Leone      Freetown   211100098

# 2d. Creating a Dataframe to capture the information given from the word document

In [20]:
teams=['Hearts of Oak','Asante Kotoko','Ebusua Dwarfs','Sekondi Hassacas','Okwahu United','Tano Bofoakwa','BA United ']
gf=[120,90,90,80,78,70,71]
ga=[35,55,60,43,39,50,55]
pts=[80,60,60,55,53,49,44]

In [21]:
dict_gh_prem_teams={'Team':teams,'GF':gf,'GA':ga,'PTS':pts}

# Printing the Team name along with Goals For (GF), Goals Against (GA) and Points (PTS).

In [22]:
df_teams=pd.DataFrame(dict_gh_prem_teams,index=[1,2,3,4,5,6,7])
df_teams

Team   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okwahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7        BA United    71  55   44

# Showing the information of the team that considered more than 30 goals

In [23]:
df_teams[df_teams['GA']>30]

Team   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okwahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7        BA United    71  55   44

# Showing the information of the team that considered less than 80 goals

In [24]:
df_teams[df_teams['GF']<80]

Team  GF  GA  PTS
5  Okwahu United  78  39   53
6  Tano Bofoakwa  70  50   49
7     BA United   71  55   44

In [25]:
df_teams[df_teams['PTS']<60]

Team  GF  GA  PTS
4  Sekondi Hassacas  80  43   55
5     Okwahu United  78  39   53
6     Tano Bofoakwa  70  50   49
7        BA United   71  55   44

# Loading the csv file data

In [26]:
bf = pd.read_csv('cars 2.csv')

# Showing the first five rows of the dataset

In [27]:
bf.head()

index  company          car_type  wheel-base  length engine-type  \
0      0    Honda       Convertible        88.6   168.8        dohc   
1      1    Honda       Convertible        88.6   168.8        dohc   
2      2    Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      3  Hyundai         Salon car        99.8   176.6         ohc   
4      4  Hyundai         Salon car        99.4   176.6         ohc   

  num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0             four             7.4    33.79614   87717.5          NaN   
1             four             7.4    33.79614  107250.0          NaN   
2              six            10.3    30.57746  107250.0          NaN   
3             four             6.8    38.62416   90675.0          NaN   
4             five             7.7    28.96812  113425.0          NaN   

   Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN

# Showing the last five rows of the dataset

In [28]:
bf.tail()

index     company   car_type  wheel-base  length engine-type  \
56     81      Toyota  Salon car        97.3   171.7         ohc   
57     82      Toyota  Salon car        97.3   171.7         ohc   
58     86      Toyota  Salon car        97.3   171.7         ohc   
59     87  Mitsubishi  Salon car       104.3   188.8         ohc   
60     88  Mitsubishi      Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km    price  Unnamed: 10  \
56             four             5.7    43.45218  51837.5          NaN   
57             four             3.5    59.54558  51967.5          NaN   
58             four             6.7    41.84284  64967.5          NaN   
59             four             7.6    37.01482  84110.0          NaN   
60             four             7.6    37.01482  87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN

# Cleaning the data and getting rid of what is not needed

In [29]:
del bf['Unnamed: 10']
del bf['Unnamed: 11']
del bf['Unnamed: 12']
del bf['Unnamed: 13']
del bf['Unnamed: 14']
del bf['index']
newdf=bf.dropna()

# Displaying the updated data

In [30]:
newdf

company          car_type  wheel-base  length engine-type  \
0        Honda       Convertible        88.6   168.8        dohc   
1        Honda       Convertible        88.6   168.8        dohc   
2        Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      Hyundai         Salon car        99.8   176.6         ohc   
4      Hyundai         Salon car        99.4   176.6         ohc   
5      Hyundai         Salon car        99.8   177.3         ohc   
6      Hyundai             Wagon       105.8   192.7         ohc   
7          Bmw         Salon car       101.2   176.8         ohc   
8          Bmw         Salon car       101.2   176.8         ohc   
9          Bmw         Salon car       101.2   176.8         ohc   
10         Bmw         Salon car       103.5   189.0         ohc   
11         Bmw         Salon car       103.5   193.8         ohc   
12         Bmw         Salon car       110.0   197.0         ohc   
13     Kantaka  Four Wheel Drive        88.4   141.1           l   
14     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     Kantaka         Salon car        94.5   158.8         ohc   
16     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     Kantaka             Wagon        96.5   157.1         ohc   
19     Kantaka         Salon car        96.5   175.4         ohc   
20     Kantaka         Salon car        96.5   169.1         ohc   
21     Kantaka         Salon car        94.3   170.7         ohc   
24     Kantaka         Salon car       113.0   199.6        dohc   
25     Kantaka         Salon car       113.0   199.6        dohc   
26     Kantaka         Salon car       102.0   191.7        ohcv   
27       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28       Mazda  Four Wheel Drive        93.1   159.1         ohc   
29       Mazda  Four Wheel Drive        93.1   159.1         ohc   
30       Mazda  Four Wheel Drive        95.3   169.0       rotor   
31       Mazda         Salon car       104.9   175.0         ohc   
32      Toyota         Salon car       110.0   190.9         ohc   
33      Toyota             Wagon       110.0   190.9         ohc   
34      Toyota         Salon car       120.9   208.1        ohcv   
35      Toyota           hardtop       112.0   199.2        ohcv   
36  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
37  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
38  Mitsubishi         Salon car        96.3   172.4         ohc   
39  Mitsubishi         Salon car        96.3   172.4         ohc   
40      Nissan         Salon car        94.5   165.3         ohc   
41      Nissan         Salon car        94.5   165.3         ohc   
42      Nissan         Salon car        94.5   165.3         ohc   
43      Nissan             Wagon        94.5   170.2         ohc   
44      Nissan         Salon car       100.4   184.6        ohcv   
45  Mitsubishi       Convertible        89.5   168.9        ohcf   
46  Mitsubishi       Convertible        89.5   168.9        ohcf   
48       Honda  Four Wheel Drive        95.7   158.7         ohc   
49       Honda  Four Wheel Drive        95.7   158.7         ohc   
50       Honda  Four Wheel Drive        95.7   158.7         ohc   
51       Honda             Wagon        95.7   169.7         ohc   
52       Honda             Wagon        95.7   169.7         ohc   
53       Honda             Wagon        95.7   169.7         ohc   
54       Honda             Wagon       104.5   187.8        dohc   
55      Toyota         Salon car        97.3   171.7         ohc   
56      Toyota         Salon car        97.3   171.7         ohc   
57      Toyota         Salon car        97.3   171.7         ohc   
58      Toyota         Salon car        97.3   171.7         ohc   
59  Mitsubishi         Salon car       104.3   188.8         ohc   
60  Mitsubishi             Wagon       104.3   188.8         oh

# Finding the most expensive car company name

In [31]:
most_expensive_car_company_name=newdf.sort_values(['price'],ascending=False).head(1)
print(most_expensive_car_company_name.iat[0,0])

Toyota


# printing out all kantanka car details

In [32]:
newdf.iloc[13:25,:]

company          car_type  wheel-base  length engine-type  \
13  Kantaka  Four Wheel Drive        88.4   141.1           l   
14  Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15  Kantaka         Salon car        94.5   158.8         ohc   
16  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18  Kantaka             Wagon        96.5   157.1         ohc   
19  Kantaka         Salon car        96.5   175.4         ohc   
20  Kantaka         Salon car        96.5   169.1         ohc   
21  Kantaka         Salon car        94.3   170.7         ohc   
24  Kantaka         Salon car       113.0   199.6        dohc   
25  Kantaka         Salon car       113.0   199.6        dohc   
26  Kantaka         Salon car       102.0   191.7        ohcv   

   num-of-cylinders  egine_capacity  average-km     price  
13            three             3.2    75.63898   33481.5  
14             four             4.7    61.15492   40917.5  
15             four             4.7    61.15492   42737.5  
16             four             4.5    49.88954   41450.5  
17             four             4.5    49.88954   40488.5  
18             four             5.1    48.28020   47417.5  
19             four             6.7    38.62416   84142.5  
20             four             6.7    40.23350   67242.5  
21             four             5.2    38.62416   44102.5  
24              six            11.7    24.14010  209625.0  
25              six            11.7    24.14010  231075.0  
26           twelve            17.5    20.92142  234000.0

# counting total cars per company

In [33]:
newdf['company'].value_counts()

Kantaka       12
Honda         10
Toyota         8
Mitsubishi     8
Bmw            6
Mazda          5
Nissan         5
Hyundai        4
Name: company, dtype: int64

# finding each company's highes price car

In [59]:
#kantanka company expensive car
kantanka_company_highest_price_car=newdf.iloc[13:25,:].sort_values(['price'],ascending=False).head(1)
print(kantanka_company_highest_price_car.iat[0,1])

Salon car


In [58]:
#hyundai company expensive car
Hyundai_hp_car = newdf[newdf.company.str.startswith('Hyundai')]
a=Hyundai_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1]) 

Wagon


In [57]:
#Nissan company expensive car
Nissan_hp_car = newdf[newdf.company.str.startswith('Nissan')]
a=Nissan_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Salon car


In [56]:
#mazda company expensive car
maza_hp_car = newdf[newdf.company.str.startswith('Mazda')]
a=maza_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Salon car


In [52]:
#Bmw company expensive car
BMW_hp_car = newdf[newdf.company.str.startswith('Bmw')]
a=BMW_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Salon car


In [49]:
#Mitsubishi company expensive car
Mitsubishi_hp_car = newdf[newdf.company.str.startswith('Mitsubishi')]
a=Mitsubishi_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Convertible


In [46]:
#Toyota company expensive car
Toyota_hp_car = newdf[newdf.company.str.startswith('Toyota')]
a=Honda_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Convertible


In [45]:
#Honda company expensive car
Honda_hp_car = newdf[newdf.company.str.startswith('Honda')]
a=Honda_hp_car.sort_values(['price'],ascending=False)
print(a.iat[0,1])

Convertible


# Find the average mileage of each car making company

# h. Sorting all cars by price column

In [40]:
newdf.sort_values(['price'],ascending=False)

company          car_type  wheel-base  length engine-type  \
35      Toyota           hardtop       112.0   199.2        ohcv   
11         Bmw         Salon car       103.5   193.8         ohc   
34      Toyota         Salon car       120.9   208.1        ohcv   
46  Mitsubishi       Convertible        89.5   168.9        ohcf   
12         Bmw         Salon car       110.0   197.0         ohc   
26     Kantaka         Salon car       102.0   191.7        ohcv   
25     Kantaka         Salon car       113.0   199.6        dohc   
45  Mitsubishi       Convertible        89.5   168.9        ohcf   
24     Kantaka         Salon car       113.0   199.6        dohc   
10         Bmw         Salon car       103.5   189.0         ohc   
33      Toyota             Wagon       110.0   190.9         ohc   
32      Toyota         Salon car       110.0   190.9         ohc   
9          Bmw         Salon car       101.2   176.8         ohc   
6      Hyundai             Wagon       105.8   192.7         ohc   
31       Mazda         Salon car       104.9   175.0         ohc   
4      Hyundai         Salon car        99.4   176.6         ohc   
8          Bmw         Salon car       101.2   176.8         ohc   
2        Honda  Four Wheel Drive        94.5   171.2        ohcv   
1        Honda       Convertible        88.6   168.8        dohc   
7          Bmw         Salon car       101.2   176.8         ohc   
54       Honda             Wagon       104.5   187.8        dohc   
5      Hyundai         Salon car        99.8   177.3         ohc   
3      Hyundai         Salon car        99.8   176.6         ohc   
44      Nissan         Salon car       100.4   184.6        ohcv   
0        Honda       Convertible        88.6   168.8        dohc   
60  Mitsubishi             Wagon       104.3   188.8         ohc   
19     Kantaka         Salon car        96.5   175.4         ohc   
59  Mitsubishi         Salon car       104.3   188.8         ohc   
30       Mazda  Four Wheel Drive        95.3   169.0       rotor   
20     Kantaka         Salon car        96.5   169.1         ohc   
58      Toyota         Salon car        97.3   171.7         ohc   
53       Honda             Wagon        95.7   169.7         ohc   
39  Mitsubishi         Salon car        96.3   172.4         ohc   
57      Toyota         Salon car        97.3   171.7         ohc   
56      Toyota         Salon car        97.3   171.7         ohc   
52       Honda             Wagon        95.7   169.7         ohc   
55      Toyota         Salon car        97.3   171.7         ohc   
43      Nissan             Wagon        94.5   170.2         ohc   
18     Kantaka             Wagon        96.5   157.1         ohc   
40      Nissan         Salon car        94.5   165.3         ohc   
38  Mitsubishi         Salon car        96.3   172.4         ohc   
51       Honda             Wagon        95.7   169.7         ohc   
42      Nissan         Salon car        94.5   165.3         ohc   
29       Mazda  Four Wheel Drive        93.1   159.1         ohc   
21     Kantaka         Salon car        94.3   170.7         ohc   
41      Nissan         Salon car        94.5   165.3         ohc   
15     Kantaka         Salon car        94.5   158.8         ohc   
50       Honda  Four Wheel Drive        95.7   158.7         ohc   
16     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
49       Honda  Four Wheel Drive        95.7   158.7         ohc   
14     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
37  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
28       Mazda  Four Wheel Drive        93.1   159.1         ohc   
36  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
48       Honda  Four Wheel Drive        95.7   158.7         ohc   
27       Mazda  Four Wheel Drive        93.1   159.1         ohc   
13     Kantaka  Four Wheel Drive        88.4   141.1           